### PR TITLE
CI: Adapt new buildme and Remove Upload to Release stage

### PR DESCRIPTION
**Pull request by stevezhengshiqi**
* ~~Add CPV build in github-action artifacts~~
* Remove Upload to Release stage because developers will upload release manually
* Fix buildme CI stage
* Update buildme code style

### CODE REVIEW

**Comment by jief666** [comment]
@stevezhengshiqi should we pull this even if checks failed ?
Why did you get rid of the validator ?

**Comment by stevezhengshiqi** [comment]
@jief666 The check failed when running `./buildme "" ci`. I believed it's related to the recent changes in buildme and other build files. The error log is at below.
```
===================== RC Scripts =======================
[BUILD] rc.scripts.on.target
[BUILD] rc.scripts.on.all.volumes
[BUILD] rc.scripts.core
================= Optional RC Scripts ==================
[BUILD] disable_sleep_proxy_client
======================== Themes ========================
[BUILD] Purple_Swirl
[BUILD] Clovy
[BUILD] BGM
[BUILD] cesium
Error can't add choice 'disable_sleep_proxy_client': a choice with same name already exists.
make: *** [pkg] Error 1
Error: Process completed with exit code 2.
```

I removed the validator because slice integrated CPV into pkg file, and he no longer provides validator in github release. For example, [Release 5135](https://github.com/CloverHackyColor/CloverBootloader/releases) did not provide validator in assets.

**Comment by jief666** [comment]
Why do you need CPV in assets when it can be compiled ? It would be better if CPV is also in the CI process, wouldn't it ?

Does this pull, like it is now, solve the problem ? Or it has to be reworked because of buildme changes ?

**Comment by stevezhengshiqi** [comment]
This CI just runs buildme to check the build process. If it fails, it means `./buildme "" ci` command can not work. I will have a deeper look at buildme later to fix the problem. If CI can build successfully, CPV will also be compiled into pkg as Slice did.

I mistakenly thought CPV will appear in assets starts from r5134. Since CPV will be compiled into pkg, we don't need CI to separately upload CPV product to GitHub artifact.

**Comment by jief666** [comment]
Hi,
Should merge this pull request as it is now ? Or some work need to be done ?

**Comment by stevezhengshiqi** [comment]
@jief666 Sorry for waiting. Should be ok now.

**Pull request merged**
