### PR TITLE
Add ExtendBTFeatureFlags to Quirks

### PR DESCRIPTION
**Pull request by z3DD3r**

### CODE REVIEW

**Comment by jief666** [comment]
Hi.
Thanks for this PR. However I may have to revert some commit. So I can't get that yet. But very soon.

**Comment by z3DD3r** [comment]
> Hi.
> Thanks for this PR. However I may have to revert some commit. So I can't get that yet. But very soon.

Got it. I've converted this PR to draft (WIP). Will do a rebase after OC 0.6.5 will be merged once again.

**Comment by jief666** [comment]
There is a small conflict. I cannot resolve because it's your repo. Once you've done it, I'll integrate your PR.
Send me a message here because I'm not sure there is notification.

**Comment by z3DD3r** [comment]
> There is a small conflict. I cannot resolve because it's your repo. Once you've done it, I'll integrate your PR.
> Send me a message here because I'm not sure there is notification.

Got it. Will do a rebase and fix conflict today.

**Comment by z3DD3r** [comment]
@jief666,
It is ready :)

**Pull request merged**
