### PR TITLE
Fix compilation on Ubuntu 18.04 / gcc 7.4.0

### PR DESCRIPTION
**Pull request by Florin9doi**
```
/usr/bin/objcopy: /home/user/Desktop/Clover/CloverBootloader/Build/Clover/RELEASE_GCC53/X64/MdeModulePkg/Universal/WatchdogTimerDxe/WatchdogTimer/DEBUG/WatchdogTimer.dll: warning: Empty loadable segment detected at vaddr=0x280, is this intentional?
[CC] ComponentName
[OBJCOPY] WatchdogTimer
GenFw: Elf64Convert.c:570: ScanSections64: Assertion `FALSE' failed.
Aborted
GNUmakefile:363: recipe for target '/home/user/Desktop/Clover/CloverBootloader/Build/Clover/RELEASE_GCC53/X64/MdeModulePkg/Universal/WatchdogTimerDxe/WatchdogTimer/OUTPUT/WatchdogTimer.efi' failed
```

### CODE REVIEW

**Comment by SergeySlice** [comment]
No, we want -flto. This conflict should be resolved other way not touching mainstream.
May be create a separate build rule for gcc-7.4?

**Comment by jief666** [comment]
It's probably a bit different, but the flag -fno-lto for GCC in /Clover/CloverEFI/OsxDxeIpl/DxeIpl.inf breaks the compilation with gcc 4.9 on High Sierra. Compilation with gcc 9 works.
Do we need that -fno-lto in that particular case ?

NOTE : the same flag appears in /Clover/CloverEFI/CpuDxe/Cpu.inf, and it does NOT break gcc 4.9 compilation.

Should I remove these -fno-lto ?

**Comment by asava** [comment]
Is any of this still relevant? I can build on Ubuntu 20.04 now without a problem.

**Comment by asava** [comment]
Will close this, as no further comments received.

**Comment by jief666** [comment]
Slice said we want lto, but "-fno-lto" seems to have been forced pushed... Is it ok ?

**Comment by Florin9doi** [comment]
A force push in a rejected PR? Is ok

**Pull request closed without merging**
