### PR TITLE
Rename '10.x' folder

### PR DESCRIPTION
**Pull request by jief666**
Rename '10.x' folder just '10' to be more consistent.

Sorry, the warning breaks the compilation. Fixed.
I didn't change the meaning of the existing folders, so for me, yes, it's compatible.
One thing I didn't think of, because I never used it, is FSInject.efi. (saw that here : https://www.insanelymac.com/forum/topic/282787-clover-v2-instructions/?tab=comments#comment-1853406).
I don't know what it is. I don't think I've ever used it. Is there any kext folder name coded in there ?

### CODE REVIEW

**Comment by jief666** [comment]
Sorry again for the unused var.
I resolved the conflict.

**Comment by jief666** [comment]
@SergeySlice : don't forgot to take this PF before some people use the master version. The name 10.x is not logical...

**Comment by SergeySlice** [comment]
Please commit this by yourself.

**Comment by jief666** [comment]
Oh yes, I forgot I can do that now.
Thanks.

**Comment by SergeySlice** [comment]
Too many messages about kexts
~~~
466:913  0:000    current kext name=Lilu.kext path=Off, match against=Other
....
~~~

**Comment by jief666** [comment]
done in PR#59

**Pull request merged**
