### PR TITLE
Corrected the Big Sur (11.0) version number

### PR DESCRIPTION
**Pull request by syscl**

### CODE REVIEW

**Comment by eskimo** [comment]
The 11.0 is purely a vanity version number right now it seems. 10.16 is what it's actually being referred to everywhere throughout the system itself.

**Comment by stevezhengshiqi** [comment]
Agree with @eskimo . I am also pretty sure that 10.16 should be the correct version number. This is what I got when I run command `sw_vers` on Big Sur:
```
ProductName: macOS
ProductVersion: 10.16
BuildVersion: 20A4299v
```

**Comment by SergeySlice** [comment]
There is no sense to change a number to another. We need to do something to make the bootloader working.

**Comment by oldman20** [comment]
> There is no sense to change a number to another. We need to do something to make the bootloader working.

now Clover can boot with Big Sur, bro?

**Comment by stevezhengshiqi** [comment]
@oldman20 No for now. Still has a long way to go. You can use the modified version provided in https://www.hackintosh-forum.de/forum/thread/49311-macos-11-bigsur-dev-beta-clover-patch/?postID=619527#post619527 as a temporary workaround.

**Comment by oldman20** [comment]
> @oldman20 No for now. Still has a long way to go. You can use the modified version provided in https://www.hackintosh-forum.de/forum/thread/49311-macos-11-bigsur-dev-beta-clover-patch/?postID=619527#post619527 as a temporary workaround.

thanks, i did before, but unsuccesfull!

**Comment by SergeySlice** [comment]
I committed bb59d21a0 with both version number 10.16 and 11.0. They are both BigSur.

**Pull request closed without merging**
