### PR TITLE
Fix nasm download and github-action update

### PR DESCRIPTION
**Pull request by stevezhengshiqi**
* build: Fix nasm link, which has been moved to ftp2
* CI: Update checkout@v4 and upload-artifact@v4

### CODE REVIEW

**Comment by chris1111** [comment]
actions/checkout@v3  Work
https://github.com/CloverHackyColor/CloverBootloader/commit/8e55dbeab3950f9706bdd655034513a9edec8096

I will test 
actions/checkout@v4

**Comment by chris1111** [comment]
actions/checkout@v4 OK
https://github.com/CloverHackyColor/CloverBootloader/commit/eff797af8d9a04d08ee04f79d7f6936ff66aba12
Thanks

**Comment by stevezhengshiqi** [comment]
@chris1111 Thank you so much for the respond.

**Comment by chris1111** [comment]
> @chris1111 Thank you so much for the respond.


Thanks to you for a week I have been trying to fix the nasm on github repos, I succeeded on Live system by downloading the nasm archive before ./buildnasm.sh because the error also occurred in sonoma 14.4 

You are the best on worflow

**Comment by stevezhengshiqi** [comment]
> > @chris1111 Thank you so much for the respond.
> 
> Thanks to you for a week I have been trying to fix the nasm on github repos, I succeeded on Live system by downloading the nasm archive before ./buildnasm.sh because the error also occurred in sonoma 14.4
> 
> You are the best on workflow

It also took me a while to find the exact issue. I tried that curl command on my local setup, and the downloaded broken file (it's actually a txt file) says they move to ftp2. Very tricky for that mirror website.

**Comment by chris1111** [comment]
> > > @chris1111 Thank you so much for the respond.
> > 
> > 
> > Thanks to you for a week I have been trying to fix the nasm on github repos, I succeeded on Live system by downloading the nasm archive before ./buildnasm.sh because the error also occurred in sonoma 14.4
> > You are the best on workflow
> 
> It also took me a while to find the exact issue. I tried that curl command on my local setup, and the downloaded broken file (it's actually a txt file) says they move to ftp2. Very tricky for that mirror website.



[All Job Pass](https://github.com/CloverHackyColor/CloverBootloader/actions/runs/8414152330)

**Comment by stevezhengshiqi** [comment]
> > > > @chris1111 Thank you so much for the respond.
> > > 
> > > 
> > > Thanks to you for a week I have been trying to fix the nasm on github repos, I succeeded on Live system by downloading the nasm archive before ./buildnasm.sh because the error also occurred in sonoma 14.4
> > > You are the best on workflow
> > 
> > 
> > It also took me a while to find the exact issue. I tried that curl command on my local setup, and the downloaded broken file (it's actually a txt file) says they move to ftp2. Very tricky for that mirror website.
> 
> [All Job Pass](https://github.com/CloverHackyColor/CloverBootloader/actions/runs/8414152330)
> 
> Background Package looks good now
> 
> Screenshot 2024-03-24 at 10 54 31 PM

That's an awesome appearance. Very beautiful design. 👍👍

**Pull request merged**
